---
title: "Assignment 1 Reproducible Research"
output: HTML_document
---



Step 1 - Load the data
```{r}
Act<-read.csv("activity.csv",header=TRUE ,na.strings="NA", stringsAsFactors=F)
ActComp<-Act[complete.cases(Act),]
```
Step 2 - Mean total number of steps per day
```{r}
sum(ActComp$steps)
hist(ActComp$steps)
mean(ActComp$steps)
median(ActComp$steps)
```
Step 3 - average daily activity pattern
```{r}
AgData<-aggregate(steps~interval,data=ActComp,FUN=mean)
plot(AgData,type="l")
AgData[which.max(AgData$steps),1]
```
Step 4 - Impute the missing data
```{r}
print(paste("Number of NAs ",sum(is.na(Act)),sep=" =  "))
library(Hmisc)
Act$interval<-impute(Act$interval,mean)
Act$steps<-impute(Act$steps,mean)
hist(Act$steps)
mean(Act$steps)
median(Act$steps)
```
There is no impact of the missing data on the mean and median of the total steps per day

Step 5 - Differences in activity pattern between weekdays and weekends
```{r}
Act$weekday<-weekdays(as.Date(Act$date))
Act[Act$weekday %in% c("Saturday","Sunday"),4]<-"Weekend"
Act[Act$weekday!="Weekend",4]<-"Weekday"
Act.weekday<-as.factor(Act$weekday)
AgWE<-aggregate(steps~interval,data=Act[Act$weekday=="Weekend",],FUN=mean)
AgWD<-aggregate(steps~interval,data=Act[Act$weekday=="Weekday",],FUN=mean)
par(mfrow=c(2,1))
plot(AgWD,type="l",main = "Steps Vs Interval(Weekdays)")
plot(AgWE,type="l",main = "Steps Vs Interval(Weekends)")
```





```{r}
n<-1000
truemean<-(1/0.2)
truevar<-(1/0.2)^2
Sample<-NULL
for (i in 1:n)
Sample[i]<-mean(rexp(40,0.2))
end
mean<-cumsum(Sample[1:n])/(1:n)

print(paste("mean of 1000 simulation means: ", mean[1000]))

print(paste("Population Mean: ", truemean))

```

You can also embed plots, for example:

```{r, echo=FALSE}
n<-1000
truemean<-(1/0.2)
truevar<-(1/0.2)^2
Sample<-NULL
for (i in 1:n)
Sample[i]<-mean(rexp(40,0.2))
end
mean<-cumsum(Sample[1:n])/(1:n)
plot(mean,xlab = "Number of Simulations")
abline(h=5)
```
